from enum import StrEnum


class RecoveryTrigger(StrEnum):
    LOW_RECOVERY = "low_recovery"
    AFTER_TRAINING = "after_training"
    LOW_ENERGY = "low_energy"
    SLEEP_DEFICIT = "sleep_deficit"
    STRESS = "stress"
    RECOVERY = "recovery"


class HabitCategory(StrEnum):
    HYDRATION = "hydration"
    SLEEP = "sleep"
    ACTIVITY = "activity"
    RECOVERY = "recovery"
    LIFESTYLE = "lifestyle"
    NUTRITION = "nutrition"


SLEEP_BASE_TEEN_MINUTES = 540
SLEEP_BASE_ADULT_MINUTES = 480
SLEEP_BASE_SENIOR_MINUTES = 450

HEAVY_LOAD_THRESHOLD = 140
VERY_HEAVY_LOAD_THRESHOLD = 180

BEGINNER_SLEEP_BONUS_MINUTES = 20
ADVANCED_SLEEP_REDUCTION_MINUTES = 10

HEAVY_LOAD_SLEEP_BONUS_MINUTES = 30
VERY_HEAVY_LOAD_SLEEP_BONUS_MINUTES = 60

SLEEP_DEBT_DAYS = 5
SLEEP_DEBT_DIVISOR = 20

SLEEP_WEIGHT = 0.45
TRAINING_WEIGHT = 0.25
HABIT_WEIGHT = 0.20
ENERGY_WEIGHT = 0.10
