# global thresholds and scoring

WEAK_MUSCLE_SCORE = 5
OVERLOAD_PENALTY = 3
PATTERN_SCORE = 2
DIFFICULTY_PENALTY = 2
DIVERSITY_BONUS = 2

LOW_DIVERSITY_THRESHOLD = 0.35
MEDIUM_DIVERSITY_THRESHOLD = 0.60

PATTERN_LOW_THRESHOLD = 0.15
PATTERN_HIGH_THRESHOLD = 0.35

PROGRESSION_MIN_WEEKS = 2
PROGRESSION_GOOD_THRESHOLD = 0.15
PROGRESSION_REGRESSION_THRESHOLD = -0.10
PROGRESSION_PLATEAU_THRESHOLD = 0.05

FREQUENCY_HIGH = 8
FREQUENCY_LOW = 2
FREQUENCY_PENALTY = 2.0
FREQUENCY_BONUS = 1.0

PROGRESSION_SCORE = 2.0
PLATEAU_SCORE = 1.0

USER_LEVEL_BEGINNER = "beginner"

SUMMARY_PRIORITY = {
    "recovery": 3,
    "load": 2,
    "muscles": 1,
    "patterns": 1,
}
