"""add training_day table

Revision ID: 18b46220f5b9
Revises: onboarding_0001
Create Date: 2026-06-09 16:12:38.580609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b46220f5b9'
down_revision = 'onboarding_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('te_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('te_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('movement_pattern', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('progression', sa.Text(), nullable=True),
    sa.Column('regression', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('te_muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('te_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('te_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_te_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('te_training_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('focus', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('te_training_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_te_training_days_plan_id'), ['plan_id'], unique=False)

    op.create_table('te_training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_te_training_plans_user_id'), ['user_id'], unique=False)

    op.create_table('te_user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('te_user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_te_user_preferences_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_te_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('te_exercise_equipment',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['te_equipment.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['te_exercises.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    op.create_table('te_exercise_muscle',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['te_exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['te_muscles.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )

    # alter existing equipment table: add tags/description first
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # add timestamps to equipment in a safe two-step way:
    # 1) add columns with server_default so existing rows get a value
    op.add_column('equipment', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')))
    op.add_column('equipment', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')))

    # 2) ensure no NULLs remain (defensive)
    op.execute("UPDATE equipment SET created_at = now() WHERE created_at IS NULL;")
    op.execute("UPDATE equipment SET updated_at = now() WHERE updated_at IS NULL;")

    # 3) make columns NOT NULL and remove server_default
    op.alter_column('equipment', 'created_at', nullable=False, server_default=None)
    op.alter_column('equipment', 'updated_at', nullable=False, server_default=None)

    # restore unique constraint on equipment.name (if not present)
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # alter users table: add timestamps in a safe two-step way and relax some columns
    # add created_at/updated_at with server_default so existing users get timestamps
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')))

    # ensure no NULLs remain
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL;")
    op.execute("UPDATE users SET updated_at = now() WHERE updated_at IS NULL;")

    # make columns NOT NULL and remove server_default
    op.alter_column('users', 'created_at', nullable=False, server_default=None)
    op.alter_column('users', 'updated_at', nullable=False, server_default=None)

    # now adjust existing user columns to be nullable as intended
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('activity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('goal',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('workouts_per_week',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # revert users alterations
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('workouts_per_week',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('activity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        # drop timestamps from users
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # revert equipment alterations
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        # drop timestamps and other columns
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('tags')

    # drop training engine tables and related indexes
    op.drop_table('te_exercise_muscle')
    op.drop_table('te_exercise_equipment')
    with op.batch_alter_table('te_user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_te_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_te_user_preferences_key'))

    op.drop_table('te_user_preferences')
    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_te_training_plans_user_id'))

    op.drop_table('te_training_plans')
    with op.batch_alter_table('te_training_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_te_training_days_plan_id'))

    op.drop_table('te_training_days')
    with op.batch_alter_table('te_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_te_sessions_user_id'))

    op.drop_table('te_sessions')
    op.drop_table('te_muscles')
    op.drop_table('te_exercises')
    op.drop_table('te_equipment')
