"""Add sleep fields to DailyRecoverySnapshot

Revision ID: 1b3d04fbc5a3
Revises: ce30a385a378
Create Date: 2026-07-24 18:05:46.396221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3d04fbc5a3'
down_revision = 'ce30a385a378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_daily_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sleep_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sleep_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_daily_snapshots', schema=None) as batch_op:
        batch_op.drop_column('sleep_end')
        batch_op.drop_column('sleep_start')
        batch_op.drop_column('sleep_duration_minutes')

    # ### end Alembic commands ###
