"""add training session models

Revision ID: 3332181752e7
Revises: 0f476ff7b9a3
Create Date: 2026-06-06 18:18:01.520357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3332181752e7'
down_revision = '0f476ff7b9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fatigue_before', sa.Float(), nullable=True),
    sa.Column('fatigue_after', sa.Float(), nullable=True),
    sa.Column('rpe_avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=64), nullable=False),
    sa.Column('sets_planned', sa.Integer(), nullable=False),
    sa.Column('sets_done', sa.Integer(), nullable=True),
    sa.Column('reps_planned', sa.String(length=32), nullable=True),
    sa.Column('reps_done', sa.String(length=32), nullable=True),
    sa.Column('load_planned', sa.Float(), nullable=True),
    sa.Column('load_done', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercises')
    op.drop_table('fitness_assessments')
    op.drop_table('workout_plans')
    op.drop_table('exercise_equipment')
    op.drop_table('training_plans')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('equipment_name_key'), type_='unique')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('equipment_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('training_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('training_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_plans_pkey'))
    )
    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('exercise_equipment_equipment_id_fkey')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercise_equipment_exercise_id_fkey')),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id', name=op.f('exercise_equipment_pkey'))
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workout_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_plans_pkey'))
    )
    op.create_table('fitness_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pushups', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('squats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plank_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('si_push', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('si_squat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('si_core', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fitness_assessments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fitness_assessments_pkey'))
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('muscle_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('strength_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_strength_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_experience', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.drop_table('session_exercises')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
