"""Create recovery models

Revision ID: 3d1772a9063f
Revises: c1ef8f8b5a2b
Create Date: 2026-07-20 18:25:46.874423

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d1772a9063f"
down_revision = "c1ef8f8b5a2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("te_exercise_equipment")
    op.drop_table("te_exercise_muscle")
    op.drop_table("recovery_plans")

    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "started_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "fatigue_before",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "fatigue_after",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "fatigue_after",
            existing_type=sa.Integer(),
            type_=sa.DOUBLE_PRECISION(precision=53),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "fatigue_before",
            existing_type=sa.Integer(),
            type_=sa.DOUBLE_PRECISION(precision=53),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "started_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.alter_column("sets_planned", existing_type=sa.INTEGER(), nullable=True)

    op.create_table(
        "recovery_plans",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("plan", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("recovery_plans_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recovery_plans_pkey")),
    )
    op.create_table(
        "te_exercise_muscle",
        sa.Column(
            "exercise_id", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
        sa.Column("muscle_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_primary", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["te_exercises.id"],
            name=op.f("te_exercise_muscle_exercise_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["muscle_id"],
            ["te_muscles.id"],
            name=op.f("te_exercise_muscle_muscle_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "exercise_id", "muscle_id", name=op.f("te_exercise_muscle_pkey")
        ),
    )
    op.create_table(
        "te_exercise_equipment",
        sa.Column(
            "exercise_id", sa.VARCHAR(length=250), autoincrement=False, nullable=False
        ),
        sa.Column("equipment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["te_equipment.id"],
            name=op.f("te_exercise_equipment_equipment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["te_exercises.id"],
            name=op.f("te_exercise_equipment_exercise_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "exercise_id", "equipment_id", name=op.f("te_exercise_equipment_pkey")
        ),
    )
    # ### end Alembic commands ###
