"""Add user_id FK to te_sessions

Revision ID: 4076b91a1199
Revises: 18b46220f5b9
Create Date: 2026-06-09 17:10:57.873269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4076b91a1199'
down_revision = '18b46220f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('te_user_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('te_user_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_te_user_equipment_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_te_user_equipment_user_id'), ['user_id'], unique=False)

    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_equipment')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('nutrition_plans_user_id_key'), type_='unique')

    with op.batch_alter_table('te_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_te_sessions_user'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('te_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_te_sessions_user'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('nutrition_plans_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('user_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('user_equipment_equipment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_equipment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_equipment_pkey'))
    )
    op.drop_table('workout_plans')
    with op.batch_alter_table('te_user_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_te_user_equipment_user_id'))
        batch_op.drop_index(batch_op.f('ix_te_user_equipment_equipment_id'))

    op.drop_table('te_user_equipment')
    # ### end Alembic commands ###
