"""empty message

Revision ID: 4c35d8208194
Revises: 4076b91a1199
Create Date: 2026-06-18 17:30:28.658422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c35d8208194'
down_revision = '4076b91a1199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_column('category_label')
        batch_op.drop_column('fiber')

    # ### end Alembic commands ###
