"""Add is_premium to User

Revision ID: 596166ca4059
Revises: c65d064d047a
Create Date: 2026-05-28 14:06:03.005579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596166ca4059'
down_revision = 'c65d064d047a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
