"""Add exercises and equipment

Revision ID: 805d60d13e7a
Revises: f72053fe3f3e
Create Date: 2026-04-27 18:46:48.521729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805d60d13e7a'
down_revision = 'f72053fe3f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('strength_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('min_strength_index', sa.Float(), nullable=False),
    sa.Column('min_experience', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    op.create_table('fitness_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pushups', sa.Integer(), nullable=False),
    sa.Column('squats', sa.Integer(), nullable=False),
    sa.Column('plank_seconds', sa.Integer(), nullable=False),
    sa.Column('si_push', sa.Float(), nullable=False),
    sa.Column('si_squat', sa.Float(), nullable=False),
    sa.Column('si_core', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_plans')
    op.drop_table('fitness_assessments')
    op.drop_table('exercise_equipment')
    op.drop_table('exercises')
    op.drop_table('equipment')
    # ### end Alembic commands ###
