"""Add recovery habit fields

Revision ID: 9302fb241b91
Revises: 1b3d04fbc5a3
Create Date: 2026-07-26 09:37:53.180201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9302fb241b91'
down_revision = '1b3d04fbc5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('daily_log_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recommended_when', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('recommended_when')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('daily_log_limit')
        batch_op.drop_column('points')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
