"""Add recovery daily snapshots table

Revision ID: ce30a385a378
Revises: 3d1772a9063f
Create Date: 2026-07-21 17:14:06.237103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce30a385a378'
down_revision = '3d1772a9063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('premium_only', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recovery_daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('habit_score', sa.Integer(), nullable=False),
    sa.Column('training_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('recovery_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_daily_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_daily_snapshots_date'), ['date'], unique=False)

    op.create_table('recovery_sleep_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes BETWEEN 1 AND 1440', name='ck_sleep_duration_range'),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 100', name='ck_sleep_quality_range'),
    sa.CheckConstraint('sleep_end > sleep_start', name='ck_sleep_time_order'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_sleep_entries', schema=None) as batch_op:
        batch_op.create_index('idx_sleep_user_date', ['user_id', 'sleep_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_sleep_entries_sleep_end'), ['sleep_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_sleep_entries_sleep_start'), ['sleep_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_sleep_entries_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_user_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['recovery_habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_habit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_habit_id'], ['recovery_user_habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('recovery_habit_logs')
    op.drop_table('recovery_user_habits')
    with op.batch_alter_table('recovery_sleep_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_sleep_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_sleep_entries_sleep_start'))
        batch_op.drop_index(batch_op.f('ix_recovery_sleep_entries_sleep_end'))
        batch_op.drop_index('idx_sleep_user_date')

    op.drop_table('recovery_sleep_entries')
    with op.batch_alter_table('recovery_daily_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_daily_snapshots_date'))

    op.drop_table('recovery_daily_snapshots')
    op.drop_table('recovery_habits')
    # ### end Alembic commands ###
