"""empty message

Revision ID: d99bc51e69e8
Revises: 4c35d8208194
Create Date: 2026-06-20 15:40:03.673846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99bc51e69e8'
down_revision = '4c35d8208194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('activity', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('goal')
        batch_op.drop_column('activity')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
