"""Add load fields and convert muscles to JSON

Revision ID: e935a13882a5
Revises: ea873e3bc158
Create Date: 2026-07-06 18:09:34.944093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e935a13882a5'
down_revision = 'ea873e3bc158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('te_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('max_additional_load_kg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('muscle_load_profile', sa.JSON(), nullable=True))
        batch_op.alter_column('muscles_primary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('muscles_secondary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('progression')
        batch_op.drop_column('regression')

    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.drop_column('meta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('te_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regression', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('progression', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('muscles_secondary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('muscles_primary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('muscle_load_profile')
        batch_op.drop_column('max_additional_load_kg')
        batch_op.drop_column('equipment')

    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
