"""fix user numeric types

Revision ID: eb4fdf6f26e1
Revises: 8f90f2e9957c
Create Date: 2026-04-23 16:56:53.052015

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eb4fdf6f26e1"
down_revision = "8f90f2e9957c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "height",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "activity",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Float(),
            existing_nullable=False,
            postgresql_using="activity::double precision",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "activity",
            existing_type=sa.Float(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "height",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
