"""empty message

Revision ID: eefb7cff2910
Revises: d99bc51e69e8
Create Date: 2026-06-20 16:02:04.215344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefb7cff2910'
down_revision = 'd99bc51e69e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('workouts_per_week', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('workouts_per_week')
        batch_op.drop_column('goal')
        batch_op.drop_column('activity')
        batch_op.drop_column('experience')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('activity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('workouts_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('workouts_per_week')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
