"""Change workout plan to JSONB

Revision ID: f72053fe3f3e
Revises: eb4fdf6f26e1
Create Date: 2026-04-24 17:17:31.151958

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f72053fe3f3e"
down_revision = "eb4fdf6f26e1"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.alter_column(
            "plan",
            existing_type=sa.TEXT(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
            postgresql_using="plan::jsonb",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.alter_column(
            "plan",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
